### ISSUE TITLE
YAML compose error in 1.1.2

### ISSUE THREAD

**Issue by paulf81** [Jakski/sphinxcontrib-autoyaml#26]
A recent attempt to build a jupyter book for documentation failed with the following error:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/sphinxcontrib/autoyaml/__init__.py", line 64, in run
    output_nodes.extend(self._parse_file(location))
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/sphinxcontrib/autoyaml/__init__.py", line 183, in _parse_file
    for doc in compose_all(source, loader):
               ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/ruamel/yaml/main.py", line 1075, in compose_all
    error_deprecation('compose', 'compose', arg=_error_dep_arg, comment=_error_dep_comment)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"compose()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.compose(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/site-packages/sphinxcontrib/autoyaml/__init__.py", line 183

        for doc in compose_all(source, loader):
```

I was able to resolve the error by setting:

`"sphinxcontrib-autoyaml==1.1.1",`

In pyproject.toml.  Is this a known issue?  Something that reflects out of date code on our end?  Or a conflict with ruamel?  Thank you!

**Comment by Jakski** [comment]
@paulf81 Issue seems to be caused by recent relaxing of `ruamel.yaml` version constraint. Please use pinned `sphinxcontrib-autoyaml` version for a while. I'll let you know in this issue when problem is fixed.

**Comment by paulf81** [comment]
thank you

**Comment by Jakski** [comment]
@paulf81 In  [1.1.3](https://pypi.org/project/sphinxcontrib-autoyaml/1.1.3/) I included fix for missing `compose_all` function in new versions of `ruamel.yaml`. After upgrading problem shouldn't occur anymore. Let me know, if that's not the case.

**Comment by paulf81** [comment]
Yes that resolved it, thank you!
